server:
  port: 9089
  
spring:
  application:
    name: PAYMENT-SERVICE
    
logging:
  file:
    name: D:\logs\ZuulAPP.log

management:
  endpoints:
    web:
      exposure:
        include: "*"

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"